/**
 * The published surface, pinned.
 *
 * `src/index.ts` is the only thing a consumer can import, so anything documented but not
 * re-exported there is broken for everyone while every other test still passes. This file asserts
 * the entry point's exports as a SET — a missing symbol and an accidental new one both fail.
 *
 * Runtime values are checked at runtime; types are erased by then, so they are checked at compile
 * time by the tuple at the bottom. `pnpm typecheck` is the gate for that half.
 */
import { expect, test } from 'vitest'
import * as sdk from './index.js'
import type {
  AddChannelInput,
  AgentChannel,
  AgentChannelCapabilitySync,
  AgentChannelCapabilities,
  ChannelPlatform,
  AgentRecord,
  AgentListParams,
  AgentPage,
  AgentPagePromise,
  AgentResource,
  AgentSkill,
  AgentStatus,
  ApprovalDecision,
  ApprovalRecord,
  CustomToolCallRecord,
  CustomToolCallStatus,
  CustomToolDeclaration,
  CustomToolResultContent,
  CustomToolResultEvent,
  CustomToolResultImageMimeType,
  CustomToolUse,
  ArtifactPage,
  ArtifactRecord,
  ArtifactStatus,
  EnvironmentConfig,
  EnvironmentRecord,
  EnvironmentResource,
  EnvironmentVersionRecord,
  ExecResult,
  FeishuPollResult,
  FeishuChannelProviderStatus,
  FeishuDocumentsCapability,
  FeishuSetupInput,
  FeishuSetupSession,
  McpServerDeclaration,
  McpContextConfig,
  McpToolPermission,
  McpToolPermissionOverride,
  ModelInfo,
  OutboundEvent,
  OutcomeConfig,
  OutcomeEvaluator,
  Ownership,
  PostEventReceipt,
  PublicInputEventType,
  SSEMessage,
  SchedulePayload,
  ScheduleRecord,
  ScheduleRun,
  ScheduleSpec,
  ScheduleUpdate,
  ScheduleInput,
  SessionEvent,
  SessionEventPage,
  SessionEventType,
  SessionHistoryEntry,
  SessionListPage,
  SessionListPageOptions,
  SessionRecord,
  SkillRecord,
  SystemPromptDeclaration,
  SystemPromptInfo,
  SystemPromptPreview,
  SystemPromptPreviewInput,
  SystemPromptUpgrade,
  UpdateChannelInput,
  ToolCall,
  WakeResult,
  SignWebhookInput,
  VerifiedWebhook,
  VerifyWebhookInput,
  WebhookApprovalEventData,
  WebhookApprovalRequestedData,
  WebhookApprovalResolvedData,
  WebhookCustomToolEventData,
  WebhookCustomToolRequestedData,
  WebhookCustomToolResolvedData,
  WebhookErrorCode,
  WebhookEvent,
  WebhookEventAttribution,
  WebhookEventData,
  WebhookEventDataByType,
  WebhookEventFor,
  WebhookEventType,
  WebhookHeaderSource,
  WebhookHeaders,
  WebhookOutcomeEvaluatedData,
  WebhookRunEventData,
  WebhookRunFinishedData,
  WebhookRunStartedData,
  WebhookRunYieldedData,
  WebhookScheduleConfigData,
  WebhookScheduleDispatchFailedData,
  WebhookScheduleDispatchedData,
  WebhookScheduleFinishedData,
  WebhookScheduleFireData,
  WebhookScheduleRunRef,
  WebhookScheduleSkippedData,
  WebhookSessionArchivedData,
  WebhookSessionCreatedData,
  WebhookSessionDeletedData,
  WebhookSignatureHeaders,
  WebhookTestData,
  WebhookWaitingOnRef,
  KnownWebhookEvent,
  ZooworkAuth,
  ZooworkClient,
  ZooworkConfig,
} from './index.js'

/** Every value the package promises. Sorted, and exhaustive in both directions. */
const PUBLIC_VALUES = [
  'DEFAULT_BASE_URL',
  'PUBLIC_INPUT_EVENT_TYPES',
  'SESSION_EVENT_TYPES',
  'WEBHOOK_DEFAULT_MAX_BODY_BYTES',
  'WEBHOOK_EVENT_TYPES',
  'WEBHOOK_ID_HEADER',
  'WEBHOOK_SCHEDULE_CONFIG_EVENT_TYPES',
  'WEBHOOK_SECRET_ENV',
  'WEBHOOK_SIGNATURE_HEADER',
  'WEBHOOK_TIMESTAMP_HEADER',
  'WEBHOOK_TOLERANCE_SECONDS',
  'ZooworkError',
  'ZooworkWebhookError',
  'assistantText',
  'createZooworkClient',
  'customToolUse',
  'isKnownWebhookEventType',
  'isRunFinished',
  'knownWebhookEvent',
  'messageText',
  'normalizeEvent',
  'parseSSE',
  'runOutcome',
  'signWebhook',
  'thinkingText',
  'toolCall',
  'unwrapWebhook',
  'verifyWebhookSignature',
]

test('the entry point exports exactly the documented value surface', () => {
  expect(Object.keys(sdk).sort()).toEqual(PUBLIC_VALUES)
})

test('every exported value is the kind of thing it claims to be', () => {
  for (const name of ['createZooworkClient', 'normalizeEvent', 'isRunFinished', 'runOutcome', 'messageText', 'assistantText', 'thinkingText', 'customToolUse', 'toolCall', 'parseSSE', 'verifyWebhookSignature', 'unwrapWebhook', 'signWebhook', 'isKnownWebhookEventType', 'knownWebhookEvent']) {
    expect(typeof (sdk as unknown as Record<string, unknown>)[name]).toBe('function')
  }
  expect(typeof sdk.DEFAULT_BASE_URL).toBe('string')
  expect(Array.isArray(sdk.SESSION_EVENT_TYPES)).toBe(true)
  expect(Array.isArray(sdk.WEBHOOK_EVENT_TYPES)).toBe(true)
  expect(Array.isArray(sdk.WEBHOOK_SCHEDULE_CONFIG_EVENT_TYPES)).toBe(true)
  // A class, not a factory: callers `instanceof` it.
  expect(new sdk.ZooworkError(404, 'x', 'not_found')).toBeInstanceOf(Error)
  expect(new sdk.ZooworkWebhookError('signature_mismatch', 'x')).toBeInstanceOf(Error)
})

test('the client built from the entry point exposes every documented method', () => {
  const client = sdk.createZooworkClient({ apiKey: 'zct_test_key', baseUrl: 'https://api.test/service/v1' })
  const methods = [
    'listModels',
    'createAgent',
    'listAgents',
    'getAgent',
    'updateAgent',
    'deleteAgent',
    'startAgent',
    'stopAgent',
    'waitUntilRunning',
    'listAgentSkills',
    'putAgentSkill',
    'deleteAgentSkill',
    'listChannels',
    'addChannel',
    'updateChannel',
    'removeChannel',
    'startChannelSetup',
    'pollChannelSetup',
    'cancelChannelSetup',
    'waitForChannelSetup',
    'startFeishuSetup',
    'pollFeishuSetup',
    'cancelFeishuSetup',
    'waitForFeishuSetup',
    'uploadSkill',
    'uploadSkillVersion',
    'listSkills',
    'deleteSkill',
    'createSession',
    'getSession',
    'listSessions',
    'listSessionPage',
    'archiveSession',
    'deleteSession',
    'postEvents',
    'listEvents',
    'listEventsPage',
    'listAllEvents',
    'streamEvents',
    'listCustomToolCalls',
    'resolveCustomToolCall',
    'listApprovals',
    'resolveApproval',
    'getSystemPrompt',
    'previewSystemPrompt',
    'upgradeSystemPrompt',
    'listArtifacts',
    'getArtifact',
    'downloadArtifact',
    'deleteArtifact',
    'listSchedules',
    'createSchedule',
    'getSchedule',
    'updateSchedule',
    'deleteSchedule',
    'triggerSchedule',
    'listScheduleRuns',
    'wake',
    'exec',
    'listEnvironments',
    'getEnvironment',
    'createEnvironment',
    'archiveEnvironment',
    'createEnvironmentVersion',
    'getEnvironmentVersion',
  ]
  expect(Object.keys(client).sort()).toEqual([...methods].sort())
})

/**
 * The type surface. Types vanish at runtime, so this tuple is the assertion: dropping any of these
 * from `src/index.ts` makes the import above unresolvable and `tsc --noEmit` fails. It is never
 * evaluated, only checked.
 */
type PublicTypes = [
  AddChannelInput,
  AgentChannel,
  AgentChannelCapabilitySync,
  AgentChannelCapabilities,
  ChannelPlatform,
  AgentRecord,
  AgentListParams,
  AgentPage,
  AgentPagePromise,
  AgentResource,
  AgentSkill,
  AgentStatus,
  ApprovalDecision,
  ApprovalRecord,
  CustomToolCallRecord,
  CustomToolCallStatus,
  CustomToolDeclaration,
  CustomToolResultContent,
  CustomToolResultEvent,
  CustomToolResultImageMimeType,
  CustomToolUse,
  ArtifactPage,
  ArtifactRecord,
  ArtifactStatus,
  EnvironmentConfig,
  EnvironmentRecord,
  EnvironmentResource,
  EnvironmentVersionRecord,
  ExecResult,
  FeishuPollResult,
  FeishuChannelProviderStatus,
  FeishuDocumentsCapability,
  FeishuSetupInput,
  FeishuSetupSession,
  McpServerDeclaration,
  McpContextConfig,
  McpToolPermission,
  McpToolPermissionOverride,
  ModelInfo,
  OutboundEvent,
  OutcomeConfig,
  OutcomeEvaluator,
  Ownership,
  PostEventReceipt,
  PublicInputEventType,
  SSEMessage,
  SchedulePayload,
  ScheduleInput,
  ScheduleRecord,
  ScheduleRun,
  ScheduleSpec,
  ScheduleUpdate,
  SessionEvent,
  SessionEventPage,
  SessionEventType,
  SessionHistoryEntry,
  SessionListPage,
  SessionListPageOptions,
  SessionRecord,
  SkillRecord,
  SystemPromptDeclaration,
  SystemPromptInfo,
  SystemPromptPreview,
  SystemPromptPreviewInput,
  SystemPromptUpgrade,
  UpdateChannelInput,
  ToolCall,
  WakeResult,
  SignWebhookInput,
  VerifiedWebhook,
  VerifyWebhookInput,
  WebhookApprovalEventData,
  WebhookApprovalRequestedData,
  WebhookApprovalResolvedData,
  WebhookCustomToolEventData,
  WebhookCustomToolRequestedData,
  WebhookCustomToolResolvedData,
  WebhookErrorCode,
  WebhookEvent,
  WebhookEventAttribution,
  // The two generics are pinned at one instantiation; that resolves the whole family.
  WebhookEventData<'run.started'>,
  WebhookEventDataByType,
  WebhookEventFor<'run.started'>,
  WebhookEventType,
  WebhookHeaderSource,
  WebhookHeaders,
  WebhookOutcomeEvaluatedData,
  WebhookRunEventData,
  WebhookRunFinishedData,
  WebhookRunStartedData,
  WebhookRunYieldedData,
  WebhookScheduleConfigData,
  WebhookScheduleDispatchFailedData,
  WebhookScheduleDispatchedData,
  WebhookScheduleFinishedData,
  WebhookScheduleFireData,
  WebhookScheduleRunRef,
  WebhookScheduleSkippedData,
  WebhookSessionArchivedData,
  WebhookSessionCreatedData,
  WebhookSessionDeletedData,
  WebhookSignatureHeaders,
  WebhookTestData,
  WebhookWaitingOnRef,
  KnownWebhookEvent,
  ZooworkAuth,
  ZooworkClient,
  ZooworkConfig,
]

test('the type surface is re-exported too (checked by tsc, counted here)', () => {
  // The tuple above cannot be measured at runtime; this keeps its length honest against the
  // import list, so adding a type to one and forgetting the other is visible in review.
  const declared: PublicTypes[number] | undefined = undefined
  expect(declared).toBeUndefined()
})
